[project]
name = "ollama-quickstart"
version = "0.1.0"
description = "A quickstart project for getting started with Ollama"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.4",
]
